### PR TITLE
Add Kluent sample

### LINKED ISSUE #35: Sample wanted for MarkusAmshove/Kluent
## About the library

- *Description*:    Fluent Assertion-Library for Kotlin 
- *GitHub*: https://github.com/MarkusAmshove/Kluent
- *Official website*: https://markusamshove.github.io/Kluent/

## What the sample could do

Add kluent examples in `src/test`, maybe follow what was done for `strikt`
https://github.com/LouisCAD/kotlin-libraries-playground/tree/main/kotlin-jvm/src/test/kotlin/framework
See also Atrium https://github.com/LouisCAD/kotlin-libraries-playground/issues/36

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

### PR DESCRIPTION
**Pull request by fejd**
Add a sample that uses the Kluent assertion library.

Resolves #35

### CODE REVIEW

**Comment by fejd** [comment]
@jmfayard I noticed that a couple of tests are failing when running ./gradlew check. Is that intentional to show output from different assertion libs? In that case maybe I shouldn't have "fixed" my test.. :)

**Comment by jmfayard** [comment]
@fejd It is intentional!
Usually you want all your tests to pass,
but a green test that pass is exactly the same in all testing frameworks
since we are testing the testing frameworks themselves,
we want to see how helpful their error messages are!

**Review by jmfayard — CHANGES_REQUESTED** [review]
Hello!
The test `DistanceConverterParameterizedTest.kt ` is useful for a framework like junit-jupiter or kotest that does parametized tests. 
But kluent is all about assertions, so what is tested here is really junit-jupiter
=> Please delete `DistanceConverterParameterizedTest`

On the other hand, I would love to have more fluent assertions in the second test file

**Review by jmfayard — APPROVED** [review]
Nice and easy to follow
I am merging it, thanks a lot @fejd !

**Pull request merged**
